/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * 
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user guide at https://docs.gradle.org/4.8.1/userguide/multi_project_builds.html
 */

rootProject.name = "adaptive-java"

include(
    ":section03:task37", ":section03:task61", ":section03:task114",
    ":section01:task165", ":section03:task56", ":section03:task53",
    ":section03:task106", ":section01:task119", ":section03:task39",
    ":section03:task49", ":section01:task164", ":section03:task43",
    ":section01:task38", ":section03:task58", ":section03:task51",
    ":section03:task54", ":section01:task60", ":section01:task64",
    ":section03:task172", ":section03:task59", ":section03:task11",
    ":section03:task38", ":section03:task45", ":section03:task62",
    ":section01:task03", ":section01:task04", ":section01:task55",
    ":section01:task76", ":section01:task21", ":section01:task129",
    ":section01:task159", ":section01:task140", ":section01:task154",
    ":section01:task06", ":section01:task39", ":section01:task40",
    ":section01:task01", ":section01:task12", ":section01:task19",
    ":section01:task126", ":section01:task26", ":section01:task58",
    ":section03:task111", ":section03:task50", ":section01:task84",
    ":section03:task63", ":section01:task167", ":section01:task123",
    ":section03:task170", ":section01:task110", ":section03:task176",
    ":section03:task64", ":section03:task77", ":section03:task14",
    ":section03:task89", ":section03:task21", ":section03:task76",
    ":section03:task16", ":section03:task89", ":section03:task21",
    ":section03:task76", ":section03:task20", ":section03:task88",
    ":section01:task94", ":section01:task194", ":section01:task51",
    ":section01:task59")
