/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * 
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user guide at https://docs.gradle.org/4.8.1/userguide/multi_project_builds.html
 */

rootProject.name = "adaptive-java"

include(":section03:task37", ":section03:task61", ":section03:task114",
    ":section01:task165", ":section03:task56", ":section03:task53", ":section03:task106",
    ":section01:task119", ":section03:task39", ":section03:task49", ":section01:task164",
    ":section03:task43", ":section01:task38", ":section03:task58", ":section03:task51",
    ":section03:task54", ":section01:task60", ":section01:task64", ":section03:task172",
    ":section03:task59", ":section03:task11", ":section03:task38", ":section03:task45",
    ":section03:task62", ":section01:task03", ":section01:task04", ":section01:task55")
